.TH GEXIMON 8 "April 7, 2004"
.SH NAME
geximon \- a Gtk2 exim MTA monitor
.SH SYNOPSIS
.B geximon
.SH DESCRIPTION
\fBgeximon\fP is a Gtk2 monitor program for the exim mail transfer agent. In
functionality it is similar to \fBeximon\fP. It has all features of the
original (tracking the log, managing the mail queue, plotting, etc.) and
more. It also integrates with \fBexiwhat\fP (allowing you to manage active
exim instances), \fBexigrep\fP, and \fBeximstats\fP. The interface is
intuitive, compact, and easy to use.
.SH OPTIONS
.TP
\fBgeximon\fP ignores all command-line arguments.
.SH SEE ALSO
.BR exim (8),
.BR eximon (8),
.BR exiwhat (8),
.BR exigrep (8),
.BR eximstats (8).
.br
.SH AUTHOR
This manual page was written by Gintautas Miliauskas <gintas@pov.lt>.
